language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty

jobs:
  include:
    - script: "mvn clean install -Dci"
    - script: "touch gremlin-dotnet/src/.glv && touch gremlin-dotnet/test/.glv mvn clean install -pl :gremlin-dotnet-tests -P gremlin-dotnet -DskipIntegrationTests=false"
