language: java
os:
  - linux
jdk:
  - oraclejdk8
sudo: required
dist: trusty
cache:
  directories:
    - $HOME/mvn-home
services:
  - docker

install:
  # install maven 3.2.5 (default minimum version for building TinkerPop) if it is not in cache already
  - bash .travis.install-maven.sh "3.2.5" "${HOME}/mvn-home"
  - export M2_HOME=${HOME}/mvn-home
  - export PATH=${HOME}/mvn-home/bin:${PATH}
  # visual check that we have the correct maven version installed
  - mvn -version

addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
#  - sudo apt-get update
#  - sudo apt-get install dotnet-dev-1.0.4
script: 
  - "docker/build.sh -t -n -i"
